# Generated by Django 5.2.3 on 2025-07-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='estado_civil',
            new_name='estadoCivil',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='fecha_cita',
            new_name='fechaCita',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='fecha_nacimiento',
            new_name='fechaNacimiento',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='hora_cita',
            new_name='horaCita',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='tipo_sangre',
            new_name='tipoSangre',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='tipo_tratamiento',
            new_name='tipoTratamiento',
        ),
        migrations.AlterField(
            model_name='cita',
            name='cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
