# Generated by Django 5.2.3 on 2025-07-16 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_rename_estado_civil_cita_estadocivil_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=225)),
                ('apellido', models.CharField(max_length=225)),
                ('cedula', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=225)),
                ('celular', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha_nacimiento')),
                ('estado_civil', models.CharField(max_length=28, verbose_name='estado civil')),
                ('edad', models.IntegerField()),
                ('tipo_sangre', models.CharField(max_length=3, null=True, verbose_name='tipo de sangre')),
                ('fecha_cita', models.DateField(max_length=225)),
                ('hora_cita', models.TimeField(max_length=1000)),
                ('tipo_tratamiento', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('cedula', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
    ]
