# Generated by Django 5.2.3 on 2025-07-16 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_pacientes_profile_delete_cita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='pacientes',
            name='correo',
            field=models.EmailField(max_length=225, null=True),
        ),
        migrations.CreateModel(
            name='cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.TimeField()),
                ('tipo_tratamiento', models.CharField(max_length=100)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.pacientes')),
            ],
        ),
    ]
