# Generated by Django 5.2.3 on 2025-07-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_rename_nombres_pacientes_nombre_pacientes_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(max_length=225)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
