# Generated by Django 5.2.3 on 2025-07-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_insumos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='insumos',
        ),
    ]
