# Generated by Django 5.2.3 on 2025-11-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nombre_documento',
            field=models.CharField(default='Documento de Observación', max_length=255),
        ),
    ]
