# Generated by Django 5.2.3 on 2025-12-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0008_documento_observaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='ultima_actualizacion',
            field=models.DateField(auto_now=True),
        ),
    ]
